# EXPLORING NUMPY

In [1]:
import numpy as np

In [6]:
l = [1,2,3,4,5]
arr = np.array(l)
type(arr)

numpy.ndarray

In [7]:
print(arr)

[1 2 3 4 5]


In [22]:
arr[2]

3

In [11]:
print(arr.shape)
print(arr.size)

(5,)
5


In [12]:
l1 = np.array(range(5))
l2 = np.array(range(2,7))
l3 = np.array(range(3,8))

In [13]:
arr1 = np.array([l1,l2,l3])

In [14]:
arr1

array([[0, 1, 2, 3, 4],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [15]:
arr1.shape

(3, 5)

In [17]:
arr1.size

15

In [18]:
arr1.reshape(5,3)

array([[0, 1, 2],
       [3, 4, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [19]:
arr1

array([[0, 1, 2, 3, 4],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [21]:
arr1.reshape(1,15)

array([[0, 1, 2, 3, 4, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

In [24]:
arr1[2][3]

6

In [26]:
arr1[:,:]

array([[0, 1, 2, 3, 4],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [27]:
arr1[0:2, 0:2]

array([[0, 1],
       [2, 3]])

In [28]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [29]:
arr1[1:, 2:4]

array([[4, 5],
       [5, 6]])

In [30]:
arr1[1:2, 1:4]

array([[3, 4, 5]])

In [33]:
ar = np.arange(11,20,2)

In [34]:
ar

array([11, 13, 15, 17, 19])

In [35]:
np.arange(0,10,step=2)

array([0, 2, 4, 6, 8])

In [37]:
np.linspace(0,20,10)#np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0,)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [41]:
#copy and broadcasting

arr

array([  1,   2, 100, 100, 100])

In [42]:
arr[2:]=200

In [43]:
arr           #referenced type

array([  1,   2, 200, 200, 200])

In [44]:
a = arr.copy()

In [45]:
a

array([  1,   2, 200, 200, 200])

In [46]:
a[3:]=90

In [47]:
a

array([  1,   2, 200,  90,  90])

In [48]:
arr

array([  1,   2, 200, 200, 200])

In [49]:
val = 2
arr<2

array([ True, False, False, False, False])

In [50]:
arr*val

array([  2,   4, 400, 400, 400])

In [51]:
arr/2

array([  0.5,   1. , 100. , 100. , 100. ])

In [52]:
arr[arr<2]

array([1])

In [53]:
arr[arr>50]

array([200, 200, 200])

In [57]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [59]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [60]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [64]:
np.random.rand(3,3)

array([[0.58391816, 0.27407855, 0.89704748],
       [0.88635679, 0.45121091, 0.4638947 ],
       [0.8703371 , 0.07179116, 0.95232324]])

In [65]:
np.random.randn(4,4)

array([[ 0.78415076,  0.20183762,  0.90090874,  0.48064109],
       [-0.64267411,  1.4771248 ,  0.06864776, -0.70833546],
       [ 0.11866786,  1.05471328, -0.16311464, -1.27452464],
       [ 0.18260065, -0.03982561, -0.5994371 , -1.04252364]])

In [68]:
np.random.randint(0,100,8) #.reshape

array([37, 64, 94, 93, 94,  9, 89, 58])

In [70]:
np.random.random_sample((1,5))

array([[0.10112942, 0.8565255 , 0.79661522, 0.33724974, 0.2641528 ]])

In [5]:
np.arange(10)*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
#broadcasting -> stretching the array to required shape
array = np.arange(10)
array+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
a = np.array([[10,20],[30,40],[50,60]])#3X2
b = np.array([1,2])#1X2
a+b

array([[11, 22],
       [31, 42],
       [51, 62]])

In [10]:
#flattening numpy arrays by flatten and ravel
#converting amongst dimensions

b = np.array([[[1,2,3],[3,4,5]], [[6,7,8],[9,10,11]]])
b

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [11]:
b.flatten()

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
b.flatten(order = 'K') #order in which elements occur in memory

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
b.flatten(order = 'A') #column and contagious in memory

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
b.flatten(order = 'F') #column major

array([ 1,  6,  3,  9,  2,  7,  4, 10,  3,  8,  5, 11])

In [15]:
b.flatten(order = 'C') #row major 

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [20]:
a.flatten(order = 'F')

array([1, 3, 2, 4])

In [23]:
#ravel() -> copy is made only if needed
#by default order is C
np.ravel(a, order='F')

array([1, 3, 2, 4])

In [24]:
b.ravel()

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

flatten() -> returns a copy, is a method

ravel()-> returns a view, is a library function

In [28]:
#transpose():
b = np.array([[1,2,3],[3,4,5],[6,7,8],[9,10,11]])
np.transpose(b, axes = None)

array([[ 1,  3,  6,  9],
       [ 2,  4,  7, 10],
       [ 3,  5,  8, 11]])

In [29]:
b

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
b = np.array([[[1,2,3],[3,4,5]], [[6,7,8],[9,10,11]]])
b.shape

(2, 2, 3)

In [31]:
np.transpose(b)

array([[[ 1,  6],
        [ 3,  9]],

       [[ 2,  7],
        [ 4, 10]],

       [[ 3,  8],
        [ 5, 11]]])

In [32]:
np.transpose(b).shape

(3, 2, 2)

In [35]:
np.transpose(np.array([1,2,3,4]))   #contains only 1 dimension

array([1, 2, 3, 4])

In [41]:
b = np.array([[1,2,3],[3,4,5],[6,7,8],[9,10,11]])
b

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
np.transpose(b, axes = (1,0)) #default

array([[ 1,  3,  6,  9],
       [ 2,  4,  7, 10],
       [ 3,  5,  8, 11]])

In [42]:
np.transpose(b, axes = (0,1))

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
a=np.arange(1,25).reshape(2,3,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [44]:
np.transpose(a, (1,2,0)) 

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [45]:
a.transpose()

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [46]:
a.T

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [49]:
#swapaxes -> interchange two dimension or axes
print(a.shape)
print(np.swapaxes(a,0,1))
print((np.swapaxes(a,0,1)).shape)

(2, 3, 4)
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]
(3, 2, 4)


In [52]:
c = np.arange(1,25).reshape(2,3,4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [51]:
np.swapaxes(c,1,2)  #c.swapaxes(1,2)

array([[[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]],

       [[13, 17, 21],
        [14, 18, 22],
        [15, 19, 23],
        [16, 20, 24]]])

swapaxes->only 2 axes

transpose-> any number

In [53]:
d=np.arange(1,5)
e=np.arange(6)

np.concatenate((d,e))

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5])

In [54]:
f = np.arange(4)
np.concatenate((d,e,f))

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3])

In [57]:
g = np.zeros(10)
np.concatenate((d,e), out=g)

array([1., 2., 3., 4., 0., 1., 2., 3., 4., 5.])

In [58]:
a = np.arange(1,5).reshape(2,2)  
b = np.arange(6,10).reshape(2,2)

In [59]:
np.concatenate((a,b))  #arrays must be of same dimension and other axes must be same

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [62]:
a = np.arange(1,5).reshape(2,2)  
b = np.array([[5,6]])

np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
np.concatenate((a,b), axis=1) #error is thrown as the axes value does not match

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [64]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [65]:
#hstack and vstack(axis=0)=combining horizontally and vertically resp.
#axis 1 - second axes

one = np.arange(6)
n = np.arange(5)
c = np.arange(5)

np.vstack((n,c))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [66]:
np.hstack((n,c))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [67]:
#axes 0 for 1 D else axes 1

In [71]:
#split()

z = np.arange(1,10)
np.split(z,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [72]:
a

array([[1, 2],
       [3, 4]])

In [73]:
np.split(a,1)

[array([[1, 2],
        [3, 4]])]

In [74]:
x = np.arange(1,13).reshape(6,2)
np.vsplit(x,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [77]:
np.hsplit(x,2)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]])]